### ISSUE TITLE
知识图谱+RAG

### ISSUE THREAD

**Issue by liuzeyu6** [xerrors/Yuxi-Know#14]
请问能否利用自己构建好的知识图谱进行RAG？

**Comment by xerrors** [comment]
可以的，需要将图谱整理成 `jsonl` 的格式，每一行都是 `{"h": "北京", "t": "中国", "r": "首都"}` 这样的格式，然后在网页的图谱管理里面添加这个文件就可以。

**Comment by FromZeroToFanatic** [comment]
大佬，如何进行知识图谱的构建呢 ，您解决了吗
