### ISSUE TITLE
知识图谱的嵌入模型

### ISSUE THREAD

**Issue by JackLittleWolf** [xerrors/Yuxi-Know#16]
知识图谱的嵌入模型一定要用zhipu-embedding-3么？Ollama的nomic-embed-text可以用么？

**Comment by xerrors** [comment]
现阶段的版本确实是只做了zhipu-embedding-3。后续会加入 Ollama 本地向量模型的支持。（也可能很久，也可能很快……）

**Comment by FromZeroToFanatic** [comment]
如何进行知识图谱的构建呢
