### ISSUE TITLE
图数据库如何管理

### ISSUE THREAD

**Issue by forbinarry** [xerrors/Yuxi-Know#17]
多个jsonl文件上传的话，图数据库如何管理呢？

**Comment by xerrors** [comment]
同时运行的图数据库只有一个，多次上传都是上传到同样的一个图谱。如果想要管理多个图谱，需要修改 neo4j 的启动参数，或者在 .env 中配置别的图数据库 uri。

**Comment by FromZeroToFanatic** [comment]
大佬，如何进行知识图谱的构建呢
