### ISSUE TITLE
.env.template文件缺失

### ISSUE THREAD

**Issue by FreshSlush** [xerrors/Yuxi-Know#18]
好像没有在src/目录下找到.env.template文件，想问一下里面都需要配置哪些变量，以及格式分别是什么呀

**Comment by xerrors** [comment]
很抱歉这一部分带来的困扰。现在建议创建 .env 文件，并添加 ZHIPUAI_API_KEY=<ZHIPUAI_API_KEY>，就可以启动该项目了。


补充说明：在项目的早期，我们使用 .env.template 来控制配置项的，但是也带来了一些不合适的地方，所以在逐步的迁移至在UI界面配置项目。.env 文件就仅仅是用来存放各个大模型平台的 API_KEY 了。
