### ISSUE TITLE
前端无法正常启动

### ISSUE THREAD

**Issue by AmbitionCX** [xerrors/Yuxi-Know#21]
按照guide运行 docker compose 之后，打开前端，页面一片空白，什么都没有。检查 console 发现一条报错信息
![image](https://github.com/user-attachments/assets/85112c45-8daf-483e-a004-123f6a9e23d1)

这里没有报错信息
```bash
sudo docker logs web-dev

> yuxi-know-frontend@0.0.0 server
> vite serve --host


  VITE v4.5.5  ready in 193 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://172.18.0.7:5173/
```

**Comment by skyfreetree** [comment]
修改index.js，使父路由和子路由的name不一样

**Comment by AmbitionCX** [comment]
嗯嗯，已经修改了，详见pr #22 Update index.js
